# Generated by Django 5.0.6 on 2024-06-14 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hod', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generate.department')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generate.department')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('min_time_taken', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_time_taken', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('assigned_staff', models.ManyToManyField(to='generate.employee')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.department')),
                ('equipment_required', models.ManyToManyField(to='generate.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Simulator_Data',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_of_queue', models.CharField(max_length=30)),
                ('no_of_patients', models.BigIntegerField()),
                ('last_simulated', models.DateTimeField(auto_now=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.department')),
            ],
        ),
    ]
