# Generated by Django 5.0.6 on 2024-06-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.department'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.department'),
        ),
    ]
