# Generated by Django 5.0.6 on 2024-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_alter_employee_dept_alter_equipment_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
    ]
