# Generated by Django 5.0.6 on 2024-06-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_equipment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
    ]
