# Generated by Django 5.0.6 on 2024-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_remove_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator_data',
            name='avg_time_per_patient',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
