# Generated by Django 5.0.6 on 2024-06-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_simulator_data_avg_time_per_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator_Meta_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doctors', models.IntegerField()),
                ('num_nurses', models.IntegerField()),
                ('num_technicians', models.IntegerField()),
                ('sim_time', models.DecimalField(decimal_places=2, max_digits=7)),
                ('seed', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Simulated Meta Data',
                'verbose_name_plural': 'Simulated Meta Data',
            },
        ),
        migrations.AlterModelOptions(
            name='simulator_data',
            options={'verbose_name': 'Simulated Data', 'verbose_name_plural': 'Simulated Data'},
        ),
        migrations.AddField(
            model_name='simulator_data',
            name='meta_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generate.simulator_meta_data'),
        ),
    ]
